services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123123
      - MYSQL_DATABASE=investment
      - MYSQL_ROOT_PASSWORD=123123